# This is a GitHub Actions workflow to deploy the application.

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean and install dependencies
        run: |
          npm ci --force
          npm rebuild

      - name: Build
        run: |
          npm run build

      - name: Deploy
        run: |
          npm run deploy
